dataset_bg_dir: None

model:
  in_channels: 384
  filters: [256, 64, 1]
  kernel_sizes: [3, 3, 1]
  strides: [1, 1, 1]
  norm: null
  activation: "lrelu"
  lang_emb_dim: 384
  film_mode: "zero"

text_embedding: "embeddings_gemini"

optim:
  lr: 0.002
  weight_decay: 0.0
  step_size: 10
  gamma: 0.75

trainer:
  batch_size: 32
  num_epochs: 50
  save_every: 5
  val_every: 5
  random_pad: true
  val_split: 0.1

criterion: "BCE"
torch_home: None
